services:
  - type: web
    name: fineartsuite
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    runtime: node
    envVars:
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: password
      - key: SESSION_SECRET
        value: gallerysecret
      - key: USE_DEMO_AUTH
        value: true
    disk:
      name: gallerydb
      mountPath: /opt/render/project/src
      sizeGB: 1
