services:
  - type: web
    name: fineartsuite
    env: node
    branch: main
    buildCommand: npm install && npm run build:css
    startCommand: npm start
    plan: free
    runtime: node
    envVars:
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: USE_DEMO_AUTH
        value: true
    disk:
      name: gallerydb
      mountPath: /opt/render/project/src
      sizeGB: 1
