-- Add columns to galleries
ALTER TABLE galleries ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE galleries ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE galleries ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE galleries ADD COLUMN IF NOT EXISTS gallarist_name TEXT;
ALTER TABLE galleries ADD COLUMN IF NOT EXISTS bio_short TEXT;
ALTER TABLE galleries ADD COLUMN IF NOT EXISTS bio_full TEXT;
ALTER TABLE galleries ADD COLUMN IF NOT EXISTS logo_url TEXT;

-- Add columns to artists
ALTER TABLE artists ADD COLUMN IF NOT EXISTS bioImageUrl TEXT;
ALTER TABLE artists ADD COLUMN IF NOT EXISTS fullBio TEXT;
ALTER TABLE artists ADD COLUMN IF NOT EXISTS bio_short TEXT;
ALTER TABLE artists ADD COLUMN IF NOT EXISTS bio_full TEXT;
ALTER TABLE artists ADD COLUMN IF NOT EXISTS portrait_url TEXT;
ALTER TABLE artists ADD COLUMN IF NOT EXISTS gallery_id TEXT;

-- Add columns to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS promo_code TEXT;

-- Add columns to artworks
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS imageFull TEXT;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS imageStandard TEXT;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS imageThumb TEXT;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS hide_collected INTEGER DEFAULT 0;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS featured INTEGER DEFAULT 0;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS isVisible INTEGER DEFAULT 1;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS isFeatured INTEGER DEFAULT 0;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS collection_id INTEGER;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS gallery_slug TEXT;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS custom_medium TEXT;
