-- Add new artwork detail columns
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS framed INTEGER DEFAULT 0;
ALTER TABLE artworks ADD COLUMN IF NOT EXISTS ready_to_hang INTEGER DEFAULT 0;
